export function Main() {
  return (
    <section data-testid="styled-jsx-card">
      <h1>Farm SWC styled-jsx plugin</h1>
      <p>Scoped styles are generated by @swc/plugin-styled-jsx.</p>
      <style jsx>{`
        section {
          padding: 32px;
          background-color: #1976d2;
          border-radius: 12px;
          color: white;
        }
      `}</style>
    </section>
  );
}
