/* generated by farmfe_plugin_react_components */
export {} 
declare global {
	const ComponentA: typeof import('./../components/ComponentA')['default']
	const ComponentG: typeof import('./../components/ComponentE')['ComponentG']
	const ComponentC: typeof import('./../components/ComponentC')['ComponentC']
	const Main: typeof import('./../test')['Main']
	const ComponentD: typeof import('./../components/ComponentD')['default']
	const Main: typeof import('./../main')['Main']
	const ComponentE: typeof import('./../components/ComponentE')['ComponentE']
	const ComponentF: typeof import('./../components/ComponentE')['ComponentF']
	const ComponentB: typeof import('./../components/ComponentB')['ComponentB']
	const ComponentX: typeof import('./../components/ComponentD')['ComponentX']
}
