/**
 * Dev server serves resources generated by the compiler, handling HMR and Lazy Compilation
 */

import { Compiler } from '../compiler';

export interface DevServerOptions {
  port: number;
}

export class DevServer {
  constructor(private compiler: Compiler, options?: DevServerOptions) {}

  listen() {
    console.log('listen');
  }
}
