[package]
name = "farmfe_plugin_sass"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { path = "../core" }
farmfe_macro_plugin = { path = "../macro_plugin" }