[package]
name = "farmfe_sourcemap"
version = "0.0.1"
edition = "2021"

[dependencies]
sourcemap = "6.2.3"
base64 = "0.21.0"

[dev-dependencies]
farmfe_testing_helpers = { path = "../testing_helpers" }
glob = "0.3"
