[package]
name = "farmfe_plugin_polyfill"
version = "0.0.3"
edition = "2021"
authors = ["brightwu(吴明亮) <1521488775@qq.com>"]
license = "MIT"
description = "Polyfill plugin of farm."
homepage = "https://farmfe.org"
repository = "https://github.com/farm-fe/farm"
documentation = "https://docs.rs/farmfe_plugin_polyfill"

[dependencies]
farmfe_core = { path = "../core", version = "0.4.4" }
farmfe_toolkit = { path = "../toolkit", version = "0.0.5" }
farmfe_testing_helpers = { path = "../testing_helpers", version = "0.0.5" }
