[package]
name = "farmfe_plugin_polyfill"
version = "0.0.1"
edition = "2021"

[dependencies]
farmfe_core = { path = "../core" }
farmfe_toolkit = { path = "../toolkit" }
farmfe_testing_helpers = { path = "../testing_helpers" }
