[package]
edition = "2021"
name = "farmfe_plugin_react"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*", path = "../../crates/core" }
farmfe_macro_plugin = { version = "*", path = "../../crates/macro_plugin" }
farmfe_toolkit_plugin_types = { version = "*", path = "../../crates/toolkit_plugin_types" }
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"

[dev-dependencies]
farmfe_testing_helpers = { path = "../../crates/testing_helpers" }
farmfe_compiler = { path = "../../crates/compiler" }
