[package]
name = "farmfe_plugin_vue_jsx"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
farmfe_core = { version = "*", path = "../../crates/core" }
farmfe_macro_plugin = { version = "*", path = "../../crates/macro_plugin" }
farmfe_toolkit_plugin_types = { version = "*", path = "../../crates/toolkit_plugin_types" }
farmfe_toolkit = { path = "../../crates/toolkit" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
farmfe_testing_helpers = { path = "../../crates/testing_helpers" }
farmfe_compiler = { path = "../../crates/compiler" }

