import { useState } from 'react';
import { css } from '@emotion/react';
import styled from 'styled-components';

const obj = {
  a: 1
};

const color = 'white';

const emotionCard = css`
  padding: 32px;
  background-color: hotpink;
  font-size: 24px;
  border-radius: 4px;
  &:hover {
    color: ${color};
  }
`;

const StyledComponentsCard = styled.section`
  padding: 32px;
  background-color: #2e7d32;
  border-radius: 16px;
  color: white;
`;

export function Main() {
  const [count, setCount] = useState(0);

  // obj.a //OK
  const a = obj?.a;

  return (
    <>
      <div
        data-testid="emotion-card"
        onClick={() => setCount((c) => c + 1)}
        css={emotionCard}
      >
        {a}: {count}
      </div>
      <StyledComponentsCard data-testid="styled-components-card">
        <h1>Farm SWC styled-components plugin</h1>
        <p>Display names and component ids are generated by @swc/plugin-styled-components.</p>
      </StyledComponentsCard>
      <section data-testid="styled-jsx-card">
        <h1>Farm SWC styled-jsx plugin</h1>
        <p>Scoped styles are generated by @swc/plugin-styled-jsx.</p>
        <style jsx>{`
          section {
            padding: 32px;
            background-color: #1976d2;
            border-radius: 12px;
            color: white;
          }
        `}</style>
      </section>
    </>
  );
}
