import styled from 'styled-components';

const Card = styled.section`
  padding: 32px;
  background-color: #2e7d32;
  border-radius: 16px;
  color: white;
`;

export function StyledComponentsCard() {
  return (
    <Card data-testid="styled-components-card">
      <h1>Farm SWC styled-components plugin</h1>
      <p>Display names and component ids are generated by @swc/plugin-styled-components.</p>
    </Card>
  );
}
