name: Building Rust Binding And Upload Artifacts
on: workflow_call

env:
  DEBUG: 'napi:*'
  MACOSX_DEPLOYMENT_TARGET: '10.13'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - target: x86_64-unknown-linux-gnu
            abi: linux-x64-gnu
          - target: x86_64-unknown-linux-musl
            abi: linux-x64-musl
          - target: x86_64-apple-darwin
            abi: darwin-x64
          - target: x86_64-pc-windows-msvc
            abi: win32-x64-msvc
          - target: i686-pc-windows-msvc
            abi: win32-ia32-msvc
          - target: aarch64-pc-windows-msvc
            abi: win32-arm64-msvc
          - target: aarch64-unknown-linux-gnu
            abi: linux-arm64-gnu
          - target: aarch64-unknown-linux-musl
            abi: linux-arm64-musl
          - target: aarch64-apple-darwin
            abi: darwin-arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: rust-build-${{ matrix.settings.abi }}
      - run: rustup target add ${{ matrix.settings.target }}
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install ziglang
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.11.0
      - run: cargo install cargo-xwin
      - run: pnpm install
      - run: pnpm build --target ${{ matrix.settings.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-${{ matrix.settings.abi }}
          path: npm/**/index.farm
          if-no-files-found: error
 