/**
 * binding.cjs and binding.d.ts are generated by the Rust. Please do not modify them manually.
 * If you want to modify the binding, please modify the Rust code or manually wrap the generated code in index.js or index.d.ts.
 */
import binding from "./binding.cjs";
import bindingPath from "./resolve-binding.cjs";
process.env.FARM_LIB_CORE_PATH = bindingPath;

// Copied from https://github.com/vercel/next.js/pull/53889/files by @BrightWu
// rust needs stdout to be blocking, otherwise it will throw an error (on macOS at least) when writing a lot of data (logs) to it
// see https://github.com/napi-rs/napi-rs/issues/1630
// and https://github.com/nodejs/node/blob/main/doc/api/process.md#a-note-on-process-io
if (process.stdout._handle != null) {
  // @ts-ignore
  process.stdout._handle.setBlocking(true);
}
if (process.stderr._handle != null) {
  // @ts-ignore
  process.stderr._handle.setBlocking(true);
}

const Compiler = binding.Compiler;
const JsFileWatcher = binding.JsFileWatcher;
export { Compiler, bindingPath, JsFileWatcher };
