/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** User defined config from js side, can be transformed from or to native Compiler config automatically */
export interface JsUserConfig {
  input: Record<string, string>;
  jsPlugins: Array<object>;
  wasmPlugins: Array<string>;
}
export const enum JsResolveKind {
  Entry = 0,
  Import = 1,
  DynamicImport = 2,
  Require = 3,
  AtImport = 4,
  Url = 5,
  ScriptSrc = 6,
  LinkHref = 7,
}
export interface JsPluginResolveHookParam {
  specifier: string;
  importer?: string;
  kind: JsResolveKind;
}
export interface JsPluginResolveHookResult {
  id: string;
  external: boolean;
  sideEffects: boolean;
}
export interface JsUpdateResult {}
export type JsCompiler = Compiler;
export class Compiler {
  constructor(config: JsUserConfig);
  /**
   * async compile, return promise
   *
   * TODO: usage example
   */
  compile(): Promise<void>;
  /** sync compile */
  compileSync(): void;
  /**
   * async update, return promise
   *
   * TODO: usage example
   */
  update(paths: Array<string>): Promise<JsUpdateResult>;
  /** sync update */
  updateSync(paths: Array<string>): JsUpdateResult;
}
