use crate::find_local_components::{ComponentInfo, ExportType};
use farmfe_toolkit::regex::Regex;
use farmfe_utils::relative;
use std::{
  fs::{self, File},
  io::{self, BufWriter, Write},
  path::Path,
};

pub struct GenerateDtsOption<'a> {
  pub components: &'a Vec<&'a ComponentInfo>,
  pub resolvers_components: &'a Vec<&'a ComponentInfo>,
  pub root_path: String,
  pub filename: String,
  pub local: bool,
}

struct DtsEntry {
  declaration_name: String,
  source: String,
  code: String,
}

pub fn remove_tsx_jsx_suffix(s: &str) -> String {
  let re = Regex::new(r"\.[tj]sx$").unwrap();
  re.replace(s, "").into_owned()
}

pub fn stringify_resolver(item: &ComponentInfo) -> String {
  let is_export_component = matches!(item.export_type, ExportType::Named);
  let mut target = "default";
  if is_export_component {
    target = &item.original_name;
  }
  format!(
    "\tconst {}: typeof import('{}')['{}']\n",
    item.name, item.path, target
  )
}

pub fn stringify_component(dts_file_path: &str, item: &ComponentInfo) -> String {
  let related = format!("./{}", relative(dts_file_path, &item.path));
  let import_path = remove_tsx_jsx_suffix(&related);
  let is_export_component = matches!(item.export_type, ExportType::Named);
  let mut target = "default";
  if is_export_component {
    target = &item.name;
  }
  format!(
    "\tconst {}: typeof import('{}')['{}']\n",
    item.name, import_path, target
  )
}

pub fn generate_dts(option: GenerateDtsOption) {
  let mut code =
    "/* generated by farmfe_plugin_react_components */\nexport {} \ndeclare global {\n".to_string();
  let dts_output = Path::new(&option.root_path).join(&option.filename);
  let mut entries = Vec::with_capacity(option.components.len() + option.resolvers_components.len());

  if option.local {
    let dts_parent = dts_output.parent().unwrap().to_str().unwrap();
    entries.extend(option.components.iter().map(|&item| DtsEntry {
      declaration_name: item.name.clone(),
      source: item.path.clone(),
      code: stringify_component(dts_parent, item),
    }));
  }

  entries.extend(option.resolvers_components.iter().map(|&item| DtsEntry {
    declaration_name: item.name.clone(),
    source: item.path.clone(),
    code: stringify_resolver(item),
  }));

  entries.sort_by(|a, b| {
    a.declaration_name
      .cmp(&b.declaration_name)
      .then_with(|| a.source.cmp(&b.source))
      .then_with(|| a.code.cmp(&b.code))
  });

  code.push_str(
    &entries
      .into_iter()
      .map(|entry| entry.code)
      .collect::<String>(),
  );

  code.push('}');

  let file = create_file(dts_output).unwrap();
  let mut writer = BufWriter::new(file);
  writeln!(writer, "{code}").unwrap();
  writer.flush().unwrap();
}

fn create_file<P: AsRef<Path>>(file_path: P) -> io::Result<File> {
  let path = file_path.as_ref();
  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent)?;
  }

  File::create(path)
}
#[cfg(test)]
mod tests {
  use super::*;
  use crate::{find_local_components::find_local_components, resolvers::get_resolvers_result};
  use std::env;
  #[test]
  fn test_generate_dts() {
    let current_dir = env::current_dir().unwrap();
    let binding = current_dir.join("playground");
    let root_path = binding.to_str().unwrap();
    let components = find_local_components(root_path, vec![]);
    let resolvers = [];
    let resolvers_components = get_resolvers_result(root_path, resolvers.to_vec());
    let generate_dts_option = GenerateDtsOption {
      components: &components.iter().collect::<Vec<_>>(),
      resolvers_components: &resolvers_components.iter().collect::<Vec<_>>(),
      root_path: root_path.to_string(),
      filename: "src/types/components.d.ts".to_string(),
      local: true,
    };
    generate_dts(generate_dts_option);
    // assert!(!components.is_empty(), "Components should not be empty");
  }
}
