/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Formatter: typeof import('./src/components/Formatter.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
    Test1: typeof import('./src/components/test1.vue')['default']
  }
}
