/* generated by farmfe_plugin_auto_import */
export {} 
declare global {
	const getName: typeof import('./../apis/index.ts')['getName']
	const name: typeof import('./../apis/name.ts')['default']
	const useOutletContext: typeof import('react-router')['useOutletContext']
	const useHref: typeof import('react-router')['useHref']
	const useInRouterContext: typeof import('react-router')['useInRouterContext']
	const useLocation: typeof import('react-router')['useLocation']
	const useNavigationType: typeof import('react-router')['useNavigationType']
	const useNavigate: typeof import('react-router')['useNavigate']
	const useOutlet: typeof import('react-router')['useOutlet']
	const useParams: typeof import('react-router')['useParams']
	const useResolvedPath: typeof import('react-router')['useResolvedPath']
	const useRoutes: typeof import('react-router')['useRoutes']
}
