name: Building Rust Binding And Upload Artifacts
on:
  workflow_call:
    inputs:
      profile:
        required: false
        type: string
        default: release

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-user:
    uses: ./.github/workflows/rust-build-user.yaml
    secrets: inherit
    with:
      profile: ${{ inputs.profile }}
  build-release:
    uses: ./.github/workflows/rust-build-release.yaml
    secrets: inherit
    with:
      profile: ${{ inputs.profile }}
