name: Check and Test
on: [pull_request]

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-10.15
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: oxidecomputer/actions-rs_toolchain@oxide/master

      - name: Run cargo check
        run: cargo check --color always --all --all-targets
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # linux tests run in coverage.yaml workflow
          - macos-10.15
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: oxidecomputer/actions-rs_toolchain@oxide/master

      - name: Run cargo test
        run: cargo test
